# Generated by Django 3.1.6 on 2021-02-10 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0003_auto_20210210_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name': 'url',
                'verbose_name_plural': 'urls',
                'db_table': 'link',
            },
        ),
        migrations.DeleteModel(
            name='UrlData',
        ),
    ]
